<?php

namespace Database\Seeders;

use App\Models\GmsStoneEnquiry;
use Illuminate\Database\Seeder;

class GmsStoneEnquirySeeder extends Seeder
{
    public function run()
    {
        $records = [
            [
                'full_name' => 'Born Cha',
                'email' => 'born@jeweal.com',
                'phone_number' => '+6699558781',
                'country_code' => 'TH',
                'account_type' => 'business',
                'business_name' => 'Jeweal GMS Stone',
                'company_name' => 'Jeweal Co., Ltd.',
                'tax_id' => '0105550000000',
                'mailing_name' => 'Born Cha',
                'website' => 'https://jeweal.com',
                'office_type' => 'Head Office',
                'branch_code' => '00000',
                'address' => 'Sukhumvit Road, Bangkok',
                'country' => 'Thailand',
                'city' => 'Bangkok',
                'province' => 'Bangkok',
                'postcode' => '10110',
                'contact_name' => 'Born Cha',
                'contact_email' => 'born@jeweal.com',
                'contact_phone' => '+6699558781',
                'is_seen' => true,
                'is_approved' => false,
            ],
            [
                'full_name' => 'Maya Tan',
                'email' => 'maya.tan@example.com',
                'phone_number' => '+6568123456',
                'country_code' => 'SG',
                'account_type' => 'business',
                'business_name' => 'Orchid Fine Gems',
                'company_name' => 'Orchid Fine Gems Pte. Ltd.',
                'tax_id' => '201912345K',
                'mailing_name' => 'Maya Tan',
                'website' => 'https://orchidgems.example.com',
                'office_type' => 'Head Office',
                'branch_code' => 'SG-HQ',
                'address' => '12 Orchard Link',
                'country' => 'Singapore',
                'city' => 'Singapore',
                'province' => 'Central',
                'postcode' => '238858',
                'contact_name' => 'Maya Tan',
                'contact_email' => 'maya.tan@example.com',
                'contact_phone' => '+6568123456',
                'is_seen' => false,
                'is_approved' => false,
            ],
            [
                'full_name' => 'Akira Sato',
                'email' => 'akira.sato@example.jp',
                'phone_number' => '+81312345678',
                'country_code' => 'JP',
                'account_type' => 'personal',
                'business_name' => null,
                'company_name' => null,
                'tax_id' => null,
                'mailing_name' => 'Akira Sato',
                'website' => null,
                'office_type' => null,
                'branch_code' => null,
                'address' => 'Shibuya, Tokyo',
                'country' => 'Japan',
                'city' => 'Tokyo',
                'province' => 'Tokyo',
                'postcode' => '150-0002',
                'contact_name' => 'Akira Sato',
                'contact_email' => 'akira.sato@example.jp',
                'contact_phone' => '+81312345678',
                'is_seen' => true,
                'is_approved' => true,
            ],
            [
                'full_name' => 'Sofia Martinez',
                'email' => 'sofia.martinez@example.es',
                'phone_number' => '+34911222333',
                'country_code' => 'ES',
                'account_type' => 'business',
                'business_name' => 'Madrid Stone Atelier',
                'company_name' => 'Madrid Stone Atelier SL',
                'tax_id' => 'B12345678',
                'mailing_name' => 'Sofia Martinez',
                'website' => 'https://madridstone.example.com',
                'office_type' => 'Branch',
                'branch_code' => 'MAD-01',
                'address' => 'Calle de Serrano 45',
                'country' => 'Spain',
                'city' => 'Madrid',
                'province' => 'Madrid',
                'postcode' => '28001',
                'contact_name' => 'Sofia Martinez',
                'contact_email' => 'sofia.martinez@example.es',
                'contact_phone' => '+34911222333',
                'is_seen' => false,
                'is_approved' => false,
            ],
            [
                'full_name' => 'Daniel Reed',
                'email' => 'daniel.reed@example.com',
                'phone_number' => '+14155550123',
                'country_code' => 'US',
                'account_type' => 'personal',
                'business_name' => null,
                'company_name' => null,
                'tax_id' => null,
                'mailing_name' => 'Daniel Reed',
                'website' => null,
                'office_type' => null,
                'branch_code' => null,
                'address' => 'Market Street, San Francisco',
                'country' => 'United States',
                'city' => 'San Francisco',
                'province' => 'California',
                'postcode' => '94103',
                'contact_name' => 'Daniel Reed',
                'contact_email' => 'daniel.reed@example.com',
                'contact_phone' => '+14155550123',
                'is_seen' => true,
                'is_approved' => false,
            ],
        ];

        foreach ($records as $record) {
            GmsStoneEnquiry::updateOrCreate(
                ['email' => $record['email']],
                $record
            );
        }
    }
}
