<?php

return [
    'default_campaign' => [
        'name' => env('GIS_FAIR_EVENT_NAME', 'The 74th Bangkok Gems & Jewelry Fair'),
        'code' => env('GIS_FAIR_EVENT_CODE', 'bgjf-74'),
        'landing_url' => env('GIS_FAIR_LANDING_URL', 'https://gis247.net/'),
        'privacy_notice_version' => env('GIS_FAIR_PRIVACY_NOTICE_VERSION', '2026-08-31'),
        'privacy_notice_url' => env('GIS_FAIR_PRIVACY_NOTICE_URL', 'https://gis247.net/privacy-policy/'),
        'contact_email' => env('GIS_FAIR_PRIVACY_EMAIL', 'privacy@gis247.net'),
    ],
    'business_types' => ['Retail', 'Wholesale', 'Manufacturing', 'Chain Store', 'Brand'],
    'current_systems' => [
        'None - spreadsheets & paper',
        'None — spreadsheets & paper',
        'In-house / custom system',
        'Another jewelry POS',
        'Lightspeed',
        'Shopify POS',
        'Square',
        'SAP',
        'Oracle NetSuite',
        'Microsoft Dynamics 365',
        'Odoo',
        'Zoho',
        'QuickBooks',
        'Other',
    ],
    'interests' => ['POS', 'ERP', 'AI', 'eCommerce', 'Inventory', 'CRM'],
    'sources' => ['gis-fair-funnel', 'design_1', 'design_2', 'design_3', 'funnel-bgjf'],
    'countries' => [
        'TH' => ['name' => 'Thailand', 'dial' => '66', 'lengths' => [10]],
        'AU' => ['name' => 'Australia', 'dial' => '61', 'lengths' => [9, 10]],
        'AT' => ['name' => 'Austria', 'dial' => '43', 'lengths' => [10, 11, 12, 13]],
        'BH' => ['name' => 'Bahrain', 'dial' => '973', 'lengths' => [8]],
        'BD' => ['name' => 'Bangladesh', 'dial' => '880', 'lengths' => [10, 11]],
        'BE' => ['name' => 'Belgium', 'dial' => '32', 'lengths' => [9, 10]],
        'BR' => ['name' => 'Brazil', 'dial' => '55', 'lengths' => [10, 11]],
        'BN' => ['name' => 'Brunei', 'dial' => '673', 'lengths' => [7]],
        'KH' => ['name' => 'Cambodia', 'dial' => '855', 'lengths' => [8, 9, 10]],
        'CA' => ['name' => 'Canada', 'dial' => '1', 'lengths' => [10], 'trunk' => ''],
        'CL' => ['name' => 'Chile', 'dial' => '56', 'lengths' => [9]],
        'CN' => ['name' => 'China', 'dial' => '86', 'lengths' => [11]],
        'CO' => ['name' => 'Colombia', 'dial' => '57', 'lengths' => [10]],
        'CZ' => ['name' => 'Czechia', 'dial' => '420', 'lengths' => [9]],
        'DK' => ['name' => 'Denmark', 'dial' => '45', 'lengths' => [8]],
        'EG' => ['name' => 'Egypt', 'dial' => '20', 'lengths' => [10, 11]],
        'FI' => ['name' => 'Finland', 'dial' => '358', 'lengths' => [9, 10]],
        'FR' => ['name' => 'France', 'dial' => '33', 'lengths' => [10]],
        'DE' => ['name' => 'Germany', 'dial' => '49', 'lengths' => [10, 11]],
        'GR' => ['name' => 'Greece', 'dial' => '30', 'lengths' => [10]],
        'HK' => ['name' => 'Hong Kong', 'dial' => '852', 'lengths' => [8], 'trunk' => ''],
        'HU' => ['name' => 'Hungary', 'dial' => '36', 'lengths' => [9]],
        'IN' => ['name' => 'India', 'dial' => '91', 'lengths' => [10]],
        'ID' => ['name' => 'Indonesia', 'dial' => '62', 'lengths' => [10, 11, 12, 13]],
        'IE' => ['name' => 'Ireland', 'dial' => '353', 'lengths' => [9, 10]],
        'IL' => ['name' => 'Israel', 'dial' => '972', 'lengths' => [9, 10]],
        'IT' => ['name' => 'Italy', 'dial' => '39', 'lengths' => [9, 10, 11]],
        'JP' => ['name' => 'Japan', 'dial' => '81', 'lengths' => [10, 11]],
        'JO' => ['name' => 'Jordan', 'dial' => '962', 'lengths' => [9, 10]],
        'KW' => ['name' => 'Kuwait', 'dial' => '965', 'lengths' => [8]],
        'LA' => ['name' => 'Laos', 'dial' => '856', 'lengths' => [9, 10]],
        'MY' => ['name' => 'Malaysia', 'dial' => '60', 'lengths' => [9, 10, 11]],
        'MX' => ['name' => 'Mexico', 'dial' => '52', 'lengths' => [10]],
        'MM' => ['name' => 'Myanmar', 'dial' => '95', 'lengths' => [8, 9, 10]],
        'NP' => ['name' => 'Nepal', 'dial' => '977', 'lengths' => [10]],
        'NL' => ['name' => 'Netherlands', 'dial' => '31', 'lengths' => [9, 10]],
        'NZ' => ['name' => 'New Zealand', 'dial' => '64', 'lengths' => [8, 9, 10]],
        'NO' => ['name' => 'Norway', 'dial' => '47', 'lengths' => [8]],
        'OM' => ['name' => 'Oman', 'dial' => '968', 'lengths' => [8]],
        'PK' => ['name' => 'Pakistan', 'dial' => '92', 'lengths' => [10, 11]],
        'PH' => ['name' => 'Philippines', 'dial' => '63', 'lengths' => [10, 11]],
        'PL' => ['name' => 'Poland', 'dial' => '48', 'lengths' => [9]],
        'PT' => ['name' => 'Portugal', 'dial' => '351', 'lengths' => [9]],
        'QA' => ['name' => 'Qatar', 'dial' => '974', 'lengths' => [8]],
        'RO' => ['name' => 'Romania', 'dial' => '40', 'lengths' => [9, 10]],
        'RU' => ['name' => 'Russia', 'dial' => '7', 'lengths' => [11], 'trunk' => '8'],
        'SA' => ['name' => 'Saudi Arabia', 'dial' => '966', 'lengths' => [9, 10]],
        'SG' => ['name' => 'Singapore', 'dial' => '65', 'lengths' => [8], 'trunk' => ''],
        'ZA' => ['name' => 'South Africa', 'dial' => '27', 'lengths' => [9, 10]],
        'KR' => ['name' => 'South Korea', 'dial' => '82', 'lengths' => [9, 10, 11]],
        'ES' => ['name' => 'Spain', 'dial' => '34', 'lengths' => [9]],
        'LK' => ['name' => 'Sri Lanka', 'dial' => '94', 'lengths' => [10]],
        'SE' => ['name' => 'Sweden', 'dial' => '46', 'lengths' => [9, 10]],
        'CH' => ['name' => 'Switzerland', 'dial' => '41', 'lengths' => [9, 10]],
        'TW' => ['name' => 'Taiwan', 'dial' => '886', 'lengths' => [9, 10]],
        'TR' => ['name' => 'Turkey', 'dial' => '90', 'lengths' => [10, 11]],
        'UA' => ['name' => 'Ukraine', 'dial' => '380', 'lengths' => [9, 10]],
        'AE' => ['name' => 'United Arab Emirates', 'dial' => '971', 'lengths' => [8, 9]],
        'GB' => ['name' => 'United Kingdom', 'dial' => '44', 'lengths' => [10, 11]],
        'US' => ['name' => 'United States', 'dial' => '1', 'lengths' => [10], 'trunk' => ''],
        'VN' => ['name' => 'Vietnam', 'dial' => '84', 'lengths' => [9, 10]],
    ],
];
